### ISSUE TITLE
Where is this going?

### ISSUE THREAD

**Issue by levino** [garbles/react-facade#1]
At a first glance this idea looks pretty neat. But it looks like this never got any traction. Any particular reason why? Is there a simpler pattern? I would think about using this for stories in a storybook, but the implementation of the hooks might get quite far from the story component (somewhere in a decorator) and the whole thing might become a little difficult to handle. Any opinions?

**Comment by garbles** [comment]
I extracted this from personal project and haven't touched it since! That said, I am happy to accept contributions in the form of bug fixes, performance improvements, documentation, tests, dependency upgrades, tooling improvements, etc.

If people are actually using this, I'll gladly maintain it; though, as you can see, you just opened issue #1. 😂

**Comment by levino** [comment]
I am first trying to understand why this solution to the problem has not been embraced by many. Usually that means there is a better solution for the problem (even though yours is neat and clever!). Or the problem itself can be avoided in total.

Since I guess this problem only occurs to people who are testing their code properly and very few people test their code properly, I assume the problem cannot be avoided or only by throwing the tests out the window (which seems to be the default solution for most such problems). I like my tests, so I started this issue to see if someone has found a better solution.

**Comment by garbles** [comment]
Yup, I like my tests too and the testing story of the modern React ecosystem is tragic. I got tired of having to choose between prop drilling or very brittle tests.

I have not found a popular/maintained solution that solves the same problem, so if anyone discovers one, I would appreciate the heads up!
